name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
          args: "--config=.golangci-lint.yml"

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
